name: shared_preferences_settings
description: Settings Screen with Shared Preferences
author: Barnab√°s BARTHA <barnabas@barthaweb.com>
repository: https://github.com/BarthaBRW/shared_preferences_settings
documentation: https://github.com/BarthaBRW/shared_preferences_settings
homepage: https://github.com/BarthaBRW/shared_preferences_settings

version: 2.1.0

environment:
  sdk: '>=3.0.0-387.0.dev <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  shared_preferences: ^2.1.0
  rxdart: ^0.27.7
  flutter_colorpicker: ^1.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0    

flutter:
  uses-material-design: true
