name: shared_preferences_settings
description: Settings Screen with Shared Preferences
author: Barnab√°s BARTHA <barnabas@barthaweb.com>
repository: https://github.com/BarthaBRW/shared_preferences_settings
documentation: https://github.com/BarthaBRW/shared_preferences_settings
homepage: https://github.com/BarthaBRW/shared_preferences_settings

version: 2.1.0

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  shared_preferences: ^2.0.7
  rxdart: ^0.27.2
  flutter_colorpicker: ^0.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
